openapi: 3.0.0
info:
  title: API Documentation
  description: CipherConvo API Documentation with swagger.
  version: 1.0
  contact:
    email: mdmuttaqin20@gmail.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  security:
    - bearerAuth: []
  responses:
    '200':
      description: OK
      content:
        application/json: {}
    '201':
      description: Created
      content:
        application/json: {}
    '404':
      description: Not Found
    '400':
      description: Bad Request
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
